ci_config:
  workspace_base: "/mnt/tests"

  raspi_controller_node: "raspi_controller_agent"
  raspi_device_node: "raspi_device_agent"

  ctrl_sdk:
    repoUrl: "git@github.com:project-chip/connectedhomeip.git"
    branch: "v1.5-branch"
    tag: ""
    sha: ""

  dut_sdk:
    repoUrl: "git@github.com:project-chip/connectedhomeip.git"
    branch: "v1.5-branch"
    tag: ""
    sha: ""

  build_config:
    ctrl:
      build_enabled: true
      docker_image: "chip-image"
      node: "local_mac_node"
    dut:
      build_enabled: true
      docker_image: "chip-image"
      node: "local_mac_node"

  copy_build_artifact:
    ctrl:
      enabled: false
      job_name: ""
      build_number: 1
    dut:
      enabled: false
      job_name: ""
      build_number: 2

  app_to_test: "all-clusters-app"

  test_run_config:
    enabled: true
    YAML:
      - TC_ONOFF_3.1.yaml
    PYTHON:
      - TC_ONOFF_3.2.py
